# Generated by Django 2.0.1 on 2018-03-20 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_by_donor', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('investigating', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('rejected', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_accepted', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=4)),
                ('family_id', models.CharField(max_length=15)),
                ('pin_code', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lattitude', models.DecimalField(decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=4)),
                ('high_volume', models.BooleanField(default=False)),
                ('pin_code', models.IntegerField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_fraudulent', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('phone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodfinder.PhoneNumber')),
                ('rejected_list', models.ManyToManyField(to='bloodfinder.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='SMSBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10)),
                ('to', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='donations',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodfinder.Donor'),
        ),
        migrations.AddField(
            model_name='donations',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodfinder.Request'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodfinder.Donor'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodfinder.PhoneNumber'),
        ),
    ]
